# Generated by Django 4.2.3 on 2023-08-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
