# Generated by Django 4.2.1 on 2023-07-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_brand_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
    ]
