# Generated by Django 4.2.1 on 2023-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/brant'),
        ),
    ]
