# Generated by Django 4.2.1 on 2023-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_brand_is_available_category_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='images',
            field=models.ImageField(upload_to='photos/brant'),
        ),
    ]
